server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: core
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**, 
        - id: supporting
          uri: http://localhost:8082
          predicates:
            - Path=/deliveries/**, /inventories/**, 
        - id: Mypage
          uri: http://localhost:8083
          predicates:
            - Path=, /dashBoards/**
        - id: sms
          uri: http://localhost:8084
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: core
          uri: http://core:8080
          predicates:
            - Path=/orders/**, 
        - id: supporting
          uri: http://supporting:8080
          predicates:
            - Path=/deliveries/**, /inventories/**, 
        - id: Mypage
          uri: http://mypage:8080
          predicates:
            - Path=, /dashBoards/**
        - id: sms
          uri: http://sms:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
